# Generated by Django 5.0.14 on 2025-06-11 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                help_text="Пользователь, написавший пост",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="Основной текст статьи", verbose_name="Содержимое"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания",
                verbose_name="Создан",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Дата и время публикации",
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                help_text="URL-идентификатор поста (только латиница, цифры, дефис)",
                max_length=250,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Черновик"), ("PB", "Опубликовано")],
                default="DF",
                help_text="Текущий статус публикации",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок поста",
                max_length=250,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего изменения",
                verbose_name="Обновлён",
            ),
        ),
    ]
