# Generated by Django 5.0.14 on 2025-06-13 21:32

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003__add_pg_trgm_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["body"],
                name="idx_post_body_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
